// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id?: string;
  created_at: string;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  user_id: string;
  username: string;
  role: string;
  token: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export enum EventType {
  CMSend = "chat.message.send",
  CMAck = "chat.message.ack",
  CMRead = "chat.message.read"
}

export type PaginatedResponse<T> = {
  previous_cursor: string | null;
  next_cursor: string | null;
  data: T[];
  limit: number;
}


export type ChatMessage = Entity<{
  id: string;
  user_id: string;
  content: string;
  seq: number;
  is_read: boolean;
}>;

export type MessageEnvelope<T> = Entity<{
  type: EventType;
  idempotency_key: string;
  message_id: string;
  session_id: string;
  payload: T;
  correlation_id: string;
  sent_at: Date;
}>

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;


export type CommonResponse<T> = {
  status_code: number;
  message: string;
  data: T
}